### ISSUE TITLE
Transfer USDC through meta tx

### ISSUE THREAD

**Issue by trnhgquan** [centrehq/centre-tokens#294]
Dear team,

I have a question here that does USDC allow user transfer USDC to other address through meta transactions (without pay gas)? If yes, could you please give me an example?

Thanks in advanced.

**Comment by danielnordh** [comment]
Paying for gas on behalf of a user would currently require a smart contract wallet instead of an EOA. I would love for this functionality to be added to the USDC contract though. 
Like the permit function on DAI; https://github.com/makerdao/dss/blob/b1fdcfc9b2ab7961bf2ce7ab4008bfcec1c73a88/src/dai.sol#L114-L138

Is this being considered?
