### ISSUE TITLE
Explanation of ERC20 deviation 

### ISSUE THREAD

**Issue by fxfactorial** [centrehq/centre-tokens#312]
Hi - can someone explain why USDC only has 6 decimal places of precision whereas most ERC 20 tokens have 18? What is the reasoning?

**Comment by omarish** [comment]
I came here with the same question. Curious as to why it wasn't either 2 (100 cents in 1 USD) or 18 (like most ERC20s)?

**Comment by petejkim** [comment]
It is unfortunate that it does not use 18 decimal places which most other tokens use. However, the ERC20 spec does not dictate that it must be 18.

USDC uses 6 decimal places because 6 was the lowest common denominator among the most popular blockchains out there and we are working on putting USDC on more chains.
